CREATE DATABASE FlashCards;




CREATE TABLE tblCARD (
CardID    INT IDENTITY(1, 1) PRIMARY KEY,
DeckID    INT,
CardName  VARCHAR(50)  NOT NULL,
CardDescr VARCHAR(500) NULL
)

CREATE TABLE tblDECK (
DeckID     INT IDENTITY(1, 1) PRIMARY KEY,
SubjectID  INT,
OwnerID    INT,
DeckName   VARCHAR(100),
DeckDescr  VARCHAR(500),
)
----
CREATE TABLE tblSUBJECT (
SubjectID    INT IDENTITY(1, 1) PRIMARY KEY,
SubjectName  VARCHAR(50),
SubjectDescr VARCHAR(500)
)

CREATE TABLE tblOWNER (
OwnerID    INT IDENTITY(1, 1) PRIMARY KEY,
OwnerFname VARCHAR(50),
OwnerLname VARCHAR(50),
OwnerDescr VARCHAR(500),
)

CREATE TABLE tblDECK_TAG (
DeckTagID INT IDENTITY(1, 1) PRIMARY KEY,
DeckID    INT,
TagID     INT,
)

CREATE TABLE tblTAG (
TagID    INT IDENTITY(1, 1) PRIMARY KEY,
TagName  VARCHAR(50),
TagDescr VARCHAR(500),
)

CREATE TABLE tblSIDE (
SideID    INT IDENTITY(1, 1) PRIMARY KEY,
SideName  VARCHAR(5),
SideDescr VARCHAR(500),
)

CREATE TABLE tblASSIGNMENT_CARD (
AssignmentCardID INT IDENTITY(1, 1) PRIMARY KEY,
CardID           INT,
AssignmentID     INT,
BeginDateTime    TIMESTAMP,  -- TIMESTAMP - format: YYYY-MM-DD HH:MM:SS
EndDateTime      DATETIME,    -- TIMESTAMP - format: YYYY-MM-DD HH:MM:SS
)

CREATE TABLE tblASSIGNMENT (
AssignmentID INT IDENTITY(1, 1) PRIMARY KEY,
DeckID       INT,
StudentID    INT,
)

CREATE TABLE tblSTUDENT (
StudentID INT IDENTITY(1, 1) PRIMARY KEY,
StudentFname VARCHAR(50) NOT NULL,
StudentLname VARCHAR(50) NOT NULL,
BirthDate    TIMESTAMP NULL,
email        VARCHAR(100) NOT NULL,
)

CREATE TABLE tblMEDIA_CARD (
MediaCardID INT IDENTITY(1, 1) PRIMARY KEY,
MediaID     INT,
CardID      INT,
SideID      INT,
Words       TEXT NULL
)

CREATE TABLE tblMEDIA (
MediaID    INT IDENTITY(1, 1) PRIMARY KEY,
MediaName  VARCHAR(30) NOT NULL,
MediaDescr VARCHAR(500) NULL,
)

CREATE TABLE tblNOTE (
NoteID      INT IDENTITY(1, 1) PRIMARY KEY,
MediaCardID INT,
NoteTypeID  INT,
NoteDate    TIMESTAMP,

)

CREATE TABLE tblNOTE_TYPE (
NoteTypeID    INT IDENTITY(1, 1) PRIMARY KEY,
NoteTypeName  VARCHAR(50),
NoteTypeDescr VARCHAR(500) NULL,
)

CREATE TABLE tblREVIEW (
ReviewID         INT IDENTITY(1, 1) PRIMARY KEY,
AssignmentCardID INT,
RatingID         INT,
IntervalID       INT,
ReviewDate       TIMESTAMP,
)

CREATE TABLE tblRATING (
RatingID   INT IDENTITY(1, 1) PRIMARY KEY,
RatingName VARCHAR(50) NULL,
)

CREATE TABLE tblINTERVAL (
IntervalID INT IDENTITY(1, 1) PRIMARY KEY,
DueDate    TIMESTAMP NOT NULL,  -- After this time u should repeat that card
--- I DON'T NEED IntervalName  AND IntervalDescr
)


-------------------
-- ALTER TABLES
--------------------

ALTER TABLE tblDECK
ADD CONSTRAINT FK_DECK_SubjectID
		FOREIGN KEY (SubjectID)
		REFERENCES tblSUBJECT(SubjectID),
    CONSTRAINT FK_DECK_OwnerID
		FOREIGN KEY (OwnerID)
		REFERENCES tblOWNER(OwnerID);

ALTER TABLE tblDECK_TAG
ADD CONSTRAINT FK_DectTag_DeckID
		FOREIGN KEY (DeckID)
		REFERENCES tblDECK(DeckID),
	CONSTRAINT FK_DeckTag_TagID
		FOREIGN KEY (TagID)
		REFERENCES tblTAG(TagID)

ALTER TABLE tblMEDIA_CARD
ADD CONSTRAINT FK_MediaCard_MediaID
		FOREIGN KEY (MediaID)
		REFERENCES tblMEDIA(MediaID),
	CONSTRAINT FK_MediaCard_CardID
		FOREIGN KEY (CardID)
		REFERENCES  tblCARD(CardID),
	CONSTRAINT FK_MediaCard_SideID
		FOREIGN KEY (SideID)
		REFERENCES tblSIDE(SideID);

ALTER TABLE tblASSIGNMENT
ADD CONSTRAINT FK_ASSIGNMENT_DeckID
		FOREIGN KEY (DeckID)
		REFERENCES tblDECK(DeckID),
	CONSTRAINT FK_ASSIGNMENT_StudentID
		FOREIGN KEY (StudentID)
		REFERENCES tblSTUDENT(StudentID);

ALTER TABLE tblASSIGNMENT_CARD
ADD CONSTRAINT FK_ASSIGNMENT_CardID
		FOREIGN KEY (CardID)
		REFERENCES tblCARD(CardID),
     CONSTRAINT FK_ASSIGNMENTCARD_AssignmentID
		FOREIGN KEY (AssignmentID)
		REFERENCES tblASSIGNMENT(AssignmentID);

ALTER TABLE tblCARD
ADD CONSTRAINT FK_tblCARD_DeckID
		FOREIGN KEY (DeckID)
		REFERENCES tblDECK(DeckID);


ALTER TABLE tblNOTE
ADD CONSTRAINT FK_tblNOTE_NoteTypeID
		FOREIGN KEY (NoteTypeID)
		REFERENCES tblNOTE_TYPE (NoteTypeID),
	CONSTRAINT FK_tblNOTE_MediaCardID
		FOREIGN KEY (MediaCardID)
		REFERENCES tblMEDIA_CARD (MediaCardID);

ALTER TABLE tblREVIEW
ADD CONSTRAINT FK_tblREVIEW_IntervalID
		FOREIGN KEY (IntervalID)
		REFERENCES tblINTERVAL (IntervalID),
	CONSTRAINT FK_tblREVIEW_RatingID
		FOREIGN KEY (RatingID)
		REFERENCES tblRATING (RatingID),
	CONSTRAINT FK_ASSIGNMENTCARD_AssignmentCardID
		FOREIGN KEY (AssignmentCardID)
		REFERENCES tblASSIGNMENT_CARD(AssignmentCardID);
